#file: .github/workflows/qa-tests.yml

name: Automated QA Tests 🤖

on: [push]

concurrency:
  group: unity_build
  cancel-in-progress: false

# See https://game.ci/docs/github/test-runner for more info
jobs:
  build:
    name: Build and run tests ✨
    runs-on: ubuntu-latest
    permissions: write-all # This is to allow writing results into the artifacts section of GitHub Actions
    steps:
      
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - name: Retrieve cached library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      # See https://game.ci/docs/github/test-runner for more information
      - name: Run tests
        id: run-unity-tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customParameters: -testCategory "E2ETests"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: PlayMode

      # Output
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results
          path: ${{ steps.run-unity-tests.outputs.artifactsPath }}