name: Unity Build and Test

on:
  # Build every commit to 'main'
  push:
    branches:
      - main

  # Build every PR
  pull_request:

concurrency:
  group: unity_build
  cancel-in-progress: false

jobs:
  test:
    name: Unity E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

#      - name: Retrieve Cached Library
#        uses: actions/cache@v3
#        with:
#          path: Library
#          key: Library-${{ hashFiles('src/RGUnityBots/Assets/**', 'src/RGUnityBots/Packages/**', 'src/RGUnityBots/ProjectSettings/**') }}
#          restore-keys: |
#            Library-

      - name: Run Unity Tests
        id: run-unity-tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: ${{ steps.run-unity-tests.outputs.artifactsPath }}
              